name: Testes Automatizados

on: [push]

jobs:
  testes:
    name: Testes TDD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
    
    - name: Instalar dependencias
      run: pip install pytest coverage
    
    - name: Rodar pytest
      run: pytest
    
    - name: Run Codecov
      run: coverage run -m pytest
    
    - name: Upload Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: e88da0e9-d9ce-4c9d-8e0d-a2467595e769